### ISSUE TITLE
UI for accessing ganga monitoring logfile

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#14]
Access to the ~/.ganga-monitoring.log  file:  add a hyperlink here but not editable (view mode)

![image](https://user-images.githubusercontent.com/621965/43320731-c2822264-91a9-11e8-9e4c-ed3c8e0f6dd5.png)

**Comment by apsknight** [comment]
Added `Logs` button in right side of header which on clicking pops up an iframe which displays logs. (Currently logs are redirected from STDOUT of Ganga session running in serverextension, not the Ganga Logger file. This issue is blocker for the above : https://github.com/apsknight/gangaextension/issues/13).

![screenshot from 2018-08-02 23-26-52](https://user-images.githubusercontent.com/19551774/43601787-b92d70fe-96ab-11e8-9e29-dfe971227864.png)
