### ISSUE TITLE
Exception: Incorrect index cache of 'jobs' object #4 was corrected!

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#25]
Tested on swan-qa004 (with previously created job). I don't know how to reproduce it.

When job is accessed there is an exception: Incorrect index cache of 'jobs' object #4 was corrected! 

This error disappeared after a while -- maybe the job was reloaded from disk?

Exception:

![image](https://user-images.githubusercontent.com/621965/43456542-28de7aa4-94c4-11e8-9b27-d051db99891d.png)

**Comment by apsknight** [comment]
Yes, it is a warning which appears due to reloading of Job object from disk. Due to this reloading, if there is any new updates, the index cache in Ganga Repository get outdated and it again updates itself hence this warning appears.

However due to fix of https://github.com/apsknight/gangaextension/issues/24, this warning will not appear now for objects in new state.

**Comment by apsknight** [comment]
Disabled this warning if sharing Jobs, added a commit in existing PR: https://github.com/ganga-devs/ganga/pull/1308/commits/d745d862c3695a82f2f7b66bf5ff2ba346a0702f
